#define TO_ILLG 0
#define TO_STR 1
#define TO_NAME 2
#define TO_DEREF 3
#define TO_ASSIGN 4
#define TO_CAST 5
#define TO_CON 6
#define TO_COMP 7
#define TO_NEGATE 8
#define TO_JMP 9
#define TO_JMPT 10
#define TO_CMPEQ 11
#define TO_CMPNE 12
#define TO_CMPLT 13
#define TO_CMPLE 14
#define TO_CMPGT 15
#define TO_CMPGE 16
#define TO_LABEL 17
#define TO_BLABEL 18
#define TO_RET 19
#define TO_LIST 20
#define TO_FUNC 21
#define TO_PLUS 22
#define TO_MINUS 23
#define TO_MUL 24
#define TO_DIV 25
#define TO_MOD 26
#define TO_OR 27
#define TO_XOR 28
#define TO_AND 29
#define TO_LS 30
#define TO_RS 31
#define TO_APLUS 32
#define TO_AMINUS 33
#define TO_AMUL 34
#define TO_ADIV 35
#define TO_AMOD 36
#define TO_AOR 37
#define TO_AXOR 38
#define TO_AAND 39
#define TO_ALS 40
#define TO_ARS 41
#define TO_PREPLUS 42
#define TO_POSTPLUS 43
#define TO_PREMINUS 44
#define TO_POSTMINUS 45
#define TO_CALL 46
#define TO_EQU 47
#define TO_FEND 48
#define TO_ALLOC 49
#define TO_REG 50

#define RELOP(x) (x <= TO_CMPGE && x >= TO_CMPEQ)
